In [1]:
# This is the bolierPlate/basic of structure of Linear Regression.

In [54]:
# Step 1: Import Libraries and Load Data
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [55]:
# Load the Iris dataset
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [56]:
# Step 2: Data Preprocessing
# In this case, the data is already clean and ready for modeling

In [57]:
# Step 3: Split Data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [58]:
# Step 4: Train Model
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [60]:
# Evaluate
y_pred = np.round(model.predict(X_test)).astype(int)
print("Linear Regression Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Linear Regression Accuracy: 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


In [62]:
# The above code is just the basic of how to use linear Regression working with real world-data and real-world-application could be very different.
#The purpose of this notebook is to give you an basic idea of how LinearRegression is used.

In [ ]:
#Thanks..